//get user address
export const GET_USER_ADDRESS_REQUEST = "GET_USER_ADDRESS_REQUEST";
export const GET_USER_ADDRESS_SUCCESS = "GET_USER_ADDRESS_SUCCESS";
export const GET_USER_ADDRESS_FAILURE = "GET_USER_ADDRESS_FAILURE";

//add user address
export const ADD_USER_ADDRESS_REQUEST = "ADD_USER_ADDRESS_REQUEST";
export const ADD_USER_ADDRESS_SUCCESS = "ADD_USER_ADDRESS_SUCCESS";
export const ADD_USER_ADDRESS_FAILURE = "ADD_USER_ADDRESS_FAILURE";

//get user order
export const GET_USER_ORDER_REQUEST = "GET_USER_ORDER_REQUEST";
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS";
export const GET_USER_ORDER_FAILURE = "GET_USER_ORDER_FAILURE";

//add user order
export const ADD_USER_ORDER_REQUEST = "ADD_USER_ORDER_REQUEST";
export const ADD_USER_ORDER_SUCCESS = "ADD_USER_ORDER_SUCCESS";
export const ADD_USER_ORDER_FAILURE = "ADD_USER_ORDER_FAILURE";

//get all order details of a user
export const GET_USER_ORDER_DETAILS_REQUEST = "GET_USER_ORDER_DETAILS_REQUEST";
export const GET_USER_ORDER_DETAILS_SUCCESS = "GET_USER_ORDER_DETAILS_SUCCESS";
export const GET_USER_ORDER_DETAILS_FAILURE = "GET_USER_ORDER_DETAILS_FAILURE";
