export const GET_PRODUCTS_BY_SLUG_REQUEST = "GET_PRODUCTS_BY_SLUG_REQUEST";
export const GET_PRODUCTS_BY_SLUG_SUCCESS = "GET_PRODUCTS_BY_SLUG_SUCCESS";
export const GET_PRODUCTS_BY_SLUG_FAILURE = "GET_PRODUCTS_BY_SLUG_FAILURE";

export const GET_PRODUCT_DETAILS_BY_ID_REQUEST = "GET_PRODUCT_DETAILS_BY_ID_REQUEST";
export const GET_PRODUCT_DETAILS_BY_ID_SUCCESS = "GET_PRODUCT_DETAILS_BY_ID_SUCCESS";
export const GET_PRODUCT_DETAILS_BY_ID_FAILURE = "GET_PRODUCT_DETAILS_BY_ID_FAILURE";
