export const GET_PRODUCTS_BY_SLUG_REQUEST = "GET_PRODUCTS_BY_SLUG_REQUEST";
export const GET_PRODUCTS_BY_SLUG_SUCCESS = "GET_PRODUCTS_BY_SLUG_SUCCESS";
export const GET_PRODUCTS_BY_SLUG_FAILURE = "GET_PRODUCTS_BY_SLUG_FAILURE";
